services:
  open_manipulator:
    container_name: open_manipulator
    build:
      context: .
      dockerfile: Dockerfile
    image: robotis/open-manipulator:latest
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    pid: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     # - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./workspace:/workspace
      - ../:/root/ros2_ws/src/open_manipulator/
    privileged: true
    command: bash
