name: ros-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main, humble ]
  pull_request:
    branches: [ main, humble ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros2-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          # - rolling
        include:
          # Humble
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # # Rolling
          # - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
          #   ros_distribution: rolling
          #   ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: open_manipulator
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
